# Generated by Django 5.1.4 on 2026-07-19 18:22

import apps.banners.models
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_price_per_day', models.DecimalField(decimal_places=2, default=Decimal('200.00'), max_digits=10)),
                ('carousel_slot_limit', models.PositiveSmallIntegerField(default=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform settings',
                'verbose_name_plural': 'Platform settings',
            },
        ),
        migrations.CreateModel(
            name='BannerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.banners.models.banner_upload_path)),
                ('headline', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('cta_label', models.CharField(default='Shop Now', max_length=40)),
                ('cta_url', models.CharField(max_length=300)),
                ('requested_days', models.PositiveSmallIntegerField()),
                ('payment_type', models.CharField(choices=[('prepaid', 'Prepaid'), ('postpaid', 'Postpaid')], max_length=10)),
                ('price_per_day_snapshot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('requested_start_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banner_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.banners.models.banner_upload_path)),
                ('headline', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('cta_label', models.CharField(max_length=40)),
                ('cta_url', models.CharField(max_length=300)),
                ('slot_position', models.PositiveSmallIntegerField()),
                ('payment_type', models.CharField(choices=[('prepaid', 'Prepaid'), ('postpaid', 'Postpaid')], max_length=10)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('days', models.PositiveSmallIntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('awaiting_payment', 'Awaiting prepayment'), ('scheduled', 'Scheduled'), ('live', 'Live'), ('completed', 'Completed'), ('overdue', 'Overdue'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('live_start_date', models.DateField(blank=True, null=True)),
                ('live_end_date', models.DateField(blank=True, null=True)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('penalty_days_elapsed', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to=settings.AUTH_USER_MODEL)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='banner', to='banners.bannerapplication')),
            ],
            options={
                'ordering': ['slot_position'],
            },
        ),
        migrations.CreateModel(
            name='BannerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='banners.banner')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banner_payments_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-paid_at'],
            },
        ),
    ]
