# Generated by Django 5.1.4 on 2026-07-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='Duo Bro Mart', max_length=100)),
                ('store_email', models.EmailField(default='hello@duobromart.pk', max_length=254)),
                ('currency', models.CharField(default='PKR', max_length=10)),
                ('default_shipping_rate', models.DecimalField(decimal_places=2, default=250, max_digits=10)),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, default=5000, max_digits=10)),
                ('handling_time', models.CharField(choices=[('same_day', 'Same Day'), ('1_2_days', '1-2 Business Days'), ('3_5_days', '3-5 Business Days')], default='1_2_days', max_length=20)),
                ('cod_enabled', models.BooleanField(default=True)),
                ('card_enabled', models.BooleanField(default=False)),
                ('jazzcash_enabled', models.BooleanField(default=False)),
                ('easypaisa_enabled', models.BooleanField(default=False)),
                ('notify_new_orders', models.BooleanField(default=True)),
                ('notify_new_vendor_applications', models.BooleanField(default=True)),
                ('notify_low_stock', models.BooleanField(default=True)),
                ('notify_payout_requests', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform settings',
                'verbose_name_plural': 'Platform settings',
            },
        ),
    ]
