# Generated by Django 5.1.4 on 2026-07-27 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_seed_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(editable=False, max_length=20, unique=True)),
                ('shipping_full_name', models.CharField(max_length=150)),
                ('shipping_phone_number', models.CharField(max_length=17)),
                ('shipping_email', models.EmailField(max_length=254)),
                ('shipping_province', models.CharField(choices=[('punjab', 'Punjab'), ('sindh', 'Sindh'), ('khyber_pakhtunkhwa', 'Khyber Pakhtunkhwa'), ('balochistan', 'Balochistan'), ('gilgit_baltistan', 'Gilgit-Baltistan'), ('azad_kashmir', 'Azad Kashmir'), ('islamabad_ct', 'Islamabad Capital Territory')], max_length=30)),
                ('shipping_city', models.CharField(max_length=100)),
                ('shipping_address_line', models.CharField(max_length=255)),
                ('shipping_is_rural', models.BooleanField(default=False)),
                ('shipping_landmark', models.CharField(blank=True, max_length=255)),
                ('billing_same_as_shipping', models.BooleanField(default=True)),
                ('billing_full_name', models.CharField(blank=True, max_length=150)),
                ('billing_phone_number', models.CharField(blank=True, max_length=17)),
                ('billing_province', models.CharField(blank=True, choices=[('punjab', 'Punjab'), ('sindh', 'Sindh'), ('khyber_pakhtunkhwa', 'Khyber Pakhtunkhwa'), ('balochistan', 'Balochistan'), ('gilgit_baltistan', 'Gilgit-Baltistan'), ('azad_kashmir', 'Azad Kashmir'), ('islamabad_ct', 'Islamabad Capital Territory')], max_length=30)),
                ('billing_city', models.CharField(blank=True, max_length=100)),
                ('billing_address_line', models.CharField(blank=True, max_length=255)),
                ('delivery_method', models.CharField(choices=[('standard', 'Standard'), ('express', 'Express'), ('urgent', 'Urgent')], default='standard', max_length=20)),
                ('payment_method', models.CharField(choices=[('cod', 'Cash on Delivery'), ('card', 'Credit/Debit Card'), ('wallet', 'Mobile Wallet')], default='cod', max_length=20)),
                ('wallet_provider', models.CharField(blank=True, help_text='NayaPay/Easypaisa/JazzCash — only for payment_method=wallet.', max_length=30)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal note, e.g. reason for cancellation.')),
                ('courier_name', models.CharField(blank=True, max_length=100)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('shipping_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estimated_delivery_days', models.PositiveSmallIntegerField(default=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, help_text='Null for a guest checkout.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_slug', models.SlugField(max_length=220)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price actually charged per unit at order time.', max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.product')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sold_order_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
