# Generated by Django 5.1.4 on 2026-07-27 23:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='unit_base_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Vendor's base_price at order time — lets commission/net-to-vendor (§6.4/§6.6) stay correct even after the product's price changes or the product itself is deleted.", max_digits=10),
        ),
    ]
