# Generated by Django 5.1.4 on 2026-08-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_idempotency_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='failed_at',
            field=models.DateTimeField(blank=True, help_text='When an admin reopened this batch after discovering the transfer actually failed outside the platform (no live bank/wallet API — see class docstring).', null=True),
        ),
        migrations.AddField(
            model_name='payout',
            name='failure_reason',
            field=models.TextField(blank=True, help_text='Why the transfer failed, entered by the admin when reopening a Paid batch (e.g. wrong account number, bank rejected transfer).'),
        ),
        migrations.AlterField(
            model_name='payout',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
