# Generated by Django 5.1.4 on 2026-08-03 20:30

import apps.feedback.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedback_order_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.feedback.models.feedback_image_upload_path, validators=[apps.feedback.models.validate_feedback_image])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='feedback.feedback')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
