# Generated by Django 5.1.4 on 2026-07-18 18:04

import apps.accounts.managers
import apps.accounts.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.accounts.managers.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='facebook_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='google_sub',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Home', max_length=50)),
                ('full_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Enter a valid Pakistani phone number, e.g. 03001234567 or +923001234567.', regex='^(\\+92|0)3\\d{9}$')])),
                ('province', models.CharField(choices=[('punjab', 'Punjab'), ('sindh', 'Sindh'), ('khyber_pakhtunkhwa', 'Khyber Pakhtunkhwa'), ('balochistan', 'Balochistan'), ('gilgit_baltistan', 'Gilgit-Baltistan'), ('azad_kashmir', 'Azad Kashmir'), ('islamabad_ct', 'Islamabad Capital Territory')], max_length=30)),
                ('city', models.CharField(max_length=100)),
                ('address_line', models.CharField(max_length=255)),
                ('landmark', models.CharField(blank=True, help_text='For rural/hard-to-find delivery (§4.4.5).', max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=apps.accounts.models._generate_token, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=apps.accounts.models._generate_token, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
