# Generated by Django 5.1.4 on 2026-07-28 10:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers_user_facebook_id_user_google_sub_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=150)),
                ('owner_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Enter a valid Pakistani phone number, e.g. 03001234567 or +923001234567.', regex='^(\\+92|0)3\\d{9}$')])),
                ('business_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('social_links', models.CharField(blank=True, max_length=255)),
                ('cnic_number', models.CharField(max_length=20)),
                ('cnic_front', models.ImageField(upload_to='vendor_applications/cnic/')),
                ('cnic_back', models.ImageField(upload_to='vendor_applications/cnic/')),
                ('bank_name', models.CharField(max_length=100)),
                ('account_title', models.CharField(max_length=150)),
                ('account_number', models.CharField(max_length=50)),
                ('account_cnic', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_vendor', models.ForeignKey(blank=True, help_text='Set on approval — the account provisioned for this applicant.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_application', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_vendor_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
