# Generated by Django 5.1.4 on 2026-08-04 10:39

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_adminmfadevice_mfarecoverycode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shop_description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='user',
            name='shop_logo',
            field=models.ImageField(blank=True, null=True, upload_to='vendor_shop/logos/', validators=[apps.accounts.models.validate_shop_logo]),
        ),
        migrations.AddField(
            model_name='user',
            name='shop_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
