# Generated by Django 5.1.4 on 2026-08-08 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_vendor_shop_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='payout_cycle_days_override',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Overrides PlatformSettings.payout_cycle_days for this vendor only. Leave blank to use the platform default.', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='payout_hold_days_override',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Overrides PlatformSettings.payout_hold_days for this vendor only. Leave blank to use the platform default.', null=True),
        ),
    ]
