# Generated by Django 5.1.4 on 2026-08-08 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Null for a guest checkout — order_item.order is the real link, verified by order_code + contact at submission time.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints_filed', to=settings.AUTH_USER_MODEL),
        ),
    ]
